### ISSUE TITLE
ch2.0-ch2.2: 캡슐화, 추상화, 상속, 다형성이 등장한 이유

### ISSUE THREAD

**Issue by ynoolee** [Dev-Prison/The-Beauty-Of-Design-Patterns#5]
- JAVA 는 왜 다중상속을 지원하지 않을까요?
- 추상화와 캡슐화의 차이는 뭘까요?

**Comment by su-pernova** [comment]
크 트리 구조로 시각화까지👏
깔끔한 정리 감사합니다 연우님!

덕타이핑이라는 개념이 흥미롭네요ㅎㅎ
